name: SFakeLags
version: '${version}'
main: org.siynes.sfakelags.SFakeLags
api-version: '1.16'
commands:
  cheatlags:
    permission: trolling.admin
    usage: /cheatlags <enable|disable> [player]
depend:
  - packetevents